### PR TITLE
UNREACHABLE_CODE.TERMINATION in vprf.c

### PR DESCRIPTION
**Pull request by g-coder**
Statements at line:253, line:258, line:263, line:295, line:334 are unreachable beacuse FatalError() function is called before the return statement. Program exits from FatalError() function because exit(1) is called from it.
return statement can be removed.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mm2: any reason why such PRs aren't merged yet?

**Comment by mm2** [comment]
Because different compilers and different code analyzers think differently about exit(). From strict point of view, this is a plain function call, so I could do a function called "exit()" that does something different. 
If I remove the return, other compilers will complain so I am not sure on what to do.

**Comment by XhmikosR** [comment]
I wasn't aware about other compilers. If that's the case I guess it's not worth adding conditionals here.

**Comment by mm2** [comment]
This is a compiler issue, the lcms code is ok.

**Pull request closed without merging**
