### PR TITLE
Change define WIN32_LEAN_AND_MEAN for windows.h in GCC

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Comment by mm2** [comment]
Thanks for your contribution. I would like, however, to underderstand the motivation of this change. Defining this symbol to 1 seems OK to me, many other software components use that. Take a look to OpenGL gl.h, for example. Windows.h accepts the current definition to 1 and it works as expected.
So, why you would  change this line?

**Comment by Jamaika1** [comment]
GCC is picky program. I use static libraries. When there are two different definitions gcc starts to redefine especially combining c and c ++ files. Originally there isn't one in windows.h.

**Comment by mm2** [comment]
This is on lcms2_internal.h which nobody but the lcms2 library should include. Aside the open source there are other proprietary parts using openGL and your change clashes with gl.h because the definitions are different. There is no benefit on the open source part at all.

**Comment by mm2** [comment]
No further comments on that, and no need of the change, so I close the PR.

**Pull request closed without merging**
