### PR TITLE
Remove and ignore Xcode & macOS temp files

### PR DESCRIPTION
**Pull request by kmilos**
According to https://github.com/github/gitignore/tree/master/Global

### CODE REVIEW

**Comment by mm2** [comment]
Thanks, this is a still work in progress... the mac folder will be deleted when Xcode project were complete. Working on the old project makes no sense anymore, it was done for powerpc in a very old machine.

**Comment by kmilos** [comment]
Sure, but polluting the git (or any repo) database with unnecessary files can affect its size and speed, so it's better to avoid it as soon as possible.

**Comment by mm2** [comment]
if you want to take a look, the project I have just committed is supposed to be the good one.

**Comment by kmilos** [comment]
Hm, I was expecting less file changes - I guess I should've merged the other way (into my branch first), but it should still work out when merged

**Review by mm2 — APPROVED** [review]

**Pull request merged**
