### PR TITLE
meson: Create separate pkgconfig files for plugins

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/mm2/Little-CMS/issues/391

### CODE REVIEW

**Comment by mm2** [comment]
Hi, please see the discussion here : https://github.com/mm2/Little-CMS/issues/391#issuecomment-1611351494

This is for me to understand why you need this. In the case you want to commercially distribute your program using the system libraries, which is something you should avoid, just not calling the plug-in init function in your program prevents any GPL'd code to be linked.  With separated pc files, you are forcing open-source clients to include a different configuration for each plug-in, which breaks compatibility with current distribution and offers nothing in exchange. Or maybe I'm missing something important?

**Comment by Biswa96** [comment]
Also, the lcms2.pc has `-llcms2 -llcms2_fast_float` in Libs field. If the program is not using the plugins, `-llcms2_fast_float` is not required.

**Comment by Biswa96** [comment]
Thanks for the explanation. I agree that there are indeed some negative side effects to consider.

**Comment by mm2** [comment]
Thanks for checking the issue!

**Comment by eli-schwartz** [comment]
> I was thinking of general use cases. For example, one can check if fastfloat or threaded plugin is available through pkgconfig files. Some projects like cairo, harfbuzz etc. have different pkgconfig files for different libraries.

I would suggest instead adding a variable `features=fastfloat,threaded` to the .pc file (in meson, pass `variables: ['features=...']` to the pkgconfig.generate() call).

People seeking to confirm which plugins are available would do the same lcms2 lookup they used to do, but this time with `--variable features` to get a list of features available.

This is also done by e.g. libcurl.pc via `supported_protocols` and `supported_features`, so it's not a novel approach.

And it has no effect on people's current usage of the pkg-config files.

**Comment by mm2** [comment]
Sure, we can add a variable on pc files, and probably that would be handy for someone, but I still like the "keep as simple as possible" approach, that's "little" CMS, remember? I guess just checking for plug-in header existence would be enough, then let the liker to do its job.

**Comment by kmilos** [comment]
> And what is being linked

As @eli-schwartz pointed out to me, the `--as-needed` linker option that you rely on here (and that was introduced as default not that long ago) might not be the default (or even available?) on all platforms and toolchains.

Perhaps you can then add it to the .pc file linker options if you're reliant on it (and the linker supports it) and want to "keep as simple as possible"?

**Comment by mm2** [comment]
I was thinking this option relates to weak references. So that means without this flag, if I link a small program by using -lm I got all math library included, no matter I only used a single floor()? 
Anyway I still think for commercial program redistribution nobody should use system libraries but local copies

**Comment by eli-schwartz** [comment]
If you statically link then the linker optimizes out anything that it can. Since you passed the unused static libraries on the command line, it does more work -- opening the archive and searching for symbols in it -- but then realizes it needs nothing, tosses it all out (or just keeps floor.o and tosses everything *else* out) and moves on.

If you dynamically link then the linker just adds a tag for the dynamic loader to load that library at runtime, which is actually needed if you use floor() -- yes, the whole library, because dynamic linking. The interesting question is what happens if you don't use any functions at all. By default the linker adds that dependency anyway, and the --as-needed flag tells it to omit the NEEDED tag in this case.

Again, this only matters when doing dynamic linking.

**Pull request closed without merging**
