### PR TITLE
Add ARM64 to Visual Studio 2019

### PR DESCRIPTION
**Pull request by gaborkertesz-linaro**
New win-arm64 platform is supported by Visual Studio 2019
as ARM64. The existing VC2019 solution was opened by
Microsoft Visual Studio Community 2019, Version 16.10.4 and ARM64
was added, based on WIN32 settings.

Tested with VS2019 build and Pillow python package on win-arm64 Win10.
https://github.com/gaborkertesz-linaro/Pillow/commit/0af6042c5c0a412c2614147458ce2d4832436bc8

### CODE REVIEW

**Comment by mm2** [comment]
Unfortunately all fast floating point plugin projects are missing ARM64. I Am trying to generate by myself.

**Comment by gaborkertesz-linaro** [comment]
Thanks and please let me know if I can help in anything!

**Comment by gaborkertesz-linaro** [comment]
Sorry for the reminder @mm2, but can I help in anything or can we merge this patch as the initial enablement for win-arm64 and add fast floating plugin as a follow-up patch?

**Comment by mm2** [comment]
I have now access to a ARM Windows 10, let's try...

**Comment by gaborkertesz-linaro** [comment]
May I ask when the next release including this change is expected?

**Comment by mm2** [comment]
Yep, I am working in the documentation, I guess it will take a week or so. Sorry, it is taking forever this time...

**Comment by gaborkertesz-linaro** [comment]
No problem, thanks!

**Comment by gaborkertesz-linaro** [comment]
Sorry for the late call, but would you prefer to add ARM64 to VS2017 as well as this was the first version to support that platform? I wasn't able to install VS2017, so I can't test it.

**Pull request merged**
